require 'capybara/cucumber'
require 'cucumber/core'
# require 'capybara/firebug/cucumber'
require 'rspec'
require 'yaml'
require 'selenium-webdriver'
# require 'faker'
# require 'facets/time'
# require 'facets/date'